package models;

// Generated 25 déc. 2014 13:37:41 by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.LazyCollection;
import org.hibernate.annotations.LazyCollectionOption;


/**
 * Groupe generated by hbm2java
 */
@Entity
@Table(name = "categorie", catalog = "news")
public class Categorie implements java.io.Serializable {

	private Integer id;
	private String nom ;
	
	private int supprime;
	private List<Article> listArticles = new ArrayList<Article>();


	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	
	@Column(name = "nom", nullable = false, length = 100)

	public String getNom() {
		return nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "supprime")
	public int getSupprime() {
		return supprime;
	}

	public void setSupprime(int supprime) {
		this.supprime = supprime;
	}
	@OneToMany(mappedBy="categorie")
	@LazyCollection(LazyCollectionOption.FALSE)
	public List<Article> getListArticles() {
		return listArticles;
	}

	public void setListArticles(List<Article> listArticles) {
		this.listArticles = listArticles;
	}

	

	

}
