package models;

// Generated 25 déc. 2014 13:37:41 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Fonctionnalitegroupe generated by hbm2java
 */
@Entity
@Table(name = "fonctionnalitegroupe", catalog = "news")
public class Fonctionnalitegroupe implements java.io.Serializable {

	private Integer id;
	private int idFonctionnalite;
	private int idGroupe;


	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "idFonctionnalite", nullable = false)
	public int getIdFonctionnalite() {
		return this.idFonctionnalite;
	}

	public void setIdFonctionnalite(int idFonctionnalite) {
		this.idFonctionnalite = idFonctionnalite;
	}

	@Column(name = "idGroupe", nullable = false)
	public int getIdGroupe() {
		return this.idGroupe;
	}

	public void setIdGroupe(int idGroupe) {
		this.idGroupe = idGroupe;
	}

}
