
package serviceweb;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "NewsSoapService", targetNamespace = "http://serviceWeb/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface NewsSoapService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.Object
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getObject", targetNamespace = "http://serviceWeb/", className = "serviceweb.GetObject")
    @ResponseWrapper(localName = "getObjectResponse", targetNamespace = "http://serviceWeb/", className = "serviceweb.GetObjectResponse")
    @Action(input = "http://serviceWeb/NewsSoapService/getObjectRequest", output = "http://serviceWeb/NewsSoapService/getObjectResponse")
    public Object getObject(
        @WebParam(name = "arg0", targetNamespace = "")
        Object arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param username
     * @return
     *     returns serviceweb.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "find", targetNamespace = "http://serviceWeb/", className = "serviceweb.Find")
    @ResponseWrapper(localName = "findResponse", targetNamespace = "http://serviceWeb/", className = "serviceweb.FindResponse")
    @Action(input = "http://serviceWeb/NewsSoapService/findRequest", output = "http://serviceWeb/NewsSoapService/findResponse")
    public User find(
        @WebParam(name = "username", targetNamespace = "")
        String username);

    /**
     * 
     * @param user
     * @return
     *     returns serviceweb.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "connect", targetNamespace = "http://serviceWeb/", className = "serviceweb.Connect")
    @ResponseWrapper(localName = "connectResponse", targetNamespace = "http://serviceWeb/", className = "serviceweb.ConnectResponse")
    @Action(input = "http://serviceWeb/NewsSoapService/connectRequest", output = "http://serviceWeb/NewsSoapService/connectResponse")
    public User connect(
        @WebParam(name = "user", targetNamespace = "http://serviceWeb/")
        User user);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "updateObject", targetNamespace = "http://serviceWeb/", className = "serviceweb.UpdateObject")
    @ResponseWrapper(localName = "updateObjectResponse", targetNamespace = "http://serviceWeb/", className = "serviceweb.UpdateObjectResponse")
    @Action(input = "http://serviceWeb/NewsSoapService/updateObjectRequest", output = "http://serviceWeb/NewsSoapService/updateObjectResponse")
    public void updateObject(
        @WebParam(name = "arg0", targetNamespace = "")
        Object arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.Object>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllObject", targetNamespace = "http://serviceWeb/", className = "serviceweb.GetAllObject")
    @ResponseWrapper(localName = "getAllObjectResponse", targetNamespace = "http://serviceWeb/", className = "serviceweb.GetAllObjectResponse")
    @Action(input = "http://serviceWeb/NewsSoapService/getAllObjectRequest", output = "http://serviceWeb/NewsSoapService/getAllObjectResponse")
    public List<Object> getAllObject(
        @WebParam(name = "arg0", targetNamespace = "")
        Object arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<serviceweb.SelectItem>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listItemGeneric", targetNamespace = "http://serviceWeb/", className = "serviceweb.ListItemGeneric")
    @ResponseWrapper(localName = "listItemGenericResponse", targetNamespace = "http://serviceWeb/", className = "serviceweb.ListItemGenericResponse")
    @Action(input = "http://serviceWeb/NewsSoapService/listItemGenericRequest", output = "http://serviceWeb/NewsSoapService/listItemGenericResponse")
    public List<SelectItem> listItemGeneric(
        @WebParam(name = "arg0", targetNamespace = "")
        Object arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "saveOrUpdateObject", targetNamespace = "http://serviceWeb/", className = "serviceweb.SaveOrUpdateObject")
    @ResponseWrapper(localName = "saveOrUpdateObjectResponse", targetNamespace = "http://serviceWeb/", className = "serviceweb.SaveOrUpdateObjectResponse")
    @Action(input = "http://serviceWeb/NewsSoapService/saveOrUpdateObjectRequest", output = "http://serviceWeb/NewsSoapService/saveOrUpdateObjectResponse")
    public void saveOrUpdateObject(
        @WebParam(name = "arg0", targetNamespace = "")
        Object arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deleteObject", targetNamespace = "http://serviceWeb/", className = "serviceweb.DeleteObject")
    @ResponseWrapper(localName = "deleteObjectResponse", targetNamespace = "http://serviceWeb/", className = "serviceweb.DeleteObjectResponse")
    @Action(input = "http://serviceWeb/NewsSoapService/deleteObjectRequest", output = "http://serviceWeb/NewsSoapService/deleteObjectResponse")
    public void deleteObject(
        @WebParam(name = "arg0", targetNamespace = "")
        Object arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "saveAllObject", targetNamespace = "http://serviceWeb/", className = "serviceweb.SaveAllObject")
    @ResponseWrapper(localName = "saveAllObjectResponse", targetNamespace = "http://serviceWeb/", className = "serviceweb.SaveAllObjectResponse")
    @Action(input = "http://serviceWeb/NewsSoapService/saveAllObjectRequest", output = "http://serviceWeb/NewsSoapService/saveAllObjectResponse")
    public void saveAllObject(
        @WebParam(name = "arg0", targetNamespace = "")
        List<Object> arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "saveObject", targetNamespace = "http://serviceWeb/", className = "serviceweb.SaveObject")
    @ResponseWrapper(localName = "saveObjectResponse", targetNamespace = "http://serviceWeb/", className = "serviceweb.SaveObjectResponse")
    @Action(input = "http://serviceWeb/NewsSoapService/saveObjectRequest", output = "http://serviceWeb/NewsSoapService/saveObjectResponse")
    public void saveObject(
        @WebParam(name = "arg0", targetNamespace = "")
        Object arg0);

}
